# Generated by Django 4.0.4 on 2022-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moverspackers', '0002_remove_siteuser_professional_remove_siteuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='shiftingdate',
            field=models.DateField(null=True),
        ),
    ]
